import type {
  AgentSidebarPublicationState,
  AgentSidebarSort,
} from "@/api/chat";

export const agentSidebarConversationKeys = {
  all: ["agents", "sidebar-conversations"] as const,
  publicationGroup: (
    projectIds: string[],
    publicationState: AgentSidebarPublicationState,
    archivedOnly: boolean,
    search = "",
    pinnedConversationIds: string[] = [],
    priorityConversationIds: string[] = [],
    sort: AgentSidebarSort = "latest"
  ) =>
    [
      ...agentSidebarConversationKeys.all,
      "publication",
      publicationState,
      "projects",
      projectIds,
      "archived",
      archivedOnly,
      "search",
      search.trim().toLowerCase(),
      "pinned",
      pinnedConversationIds,
      "priority",
      priorityConversationIds,
      "sort",
      sort,
    ] as const,
  projectGroup: (
    projectId: string | null | undefined,
    archivedOnly: boolean,
    search = "",
    publicationStates: AgentSidebarPublicationState[] = [],
    pinnedConversationIds: string[] = [],
    priorityConversationIds: string[] = []
  ) =>
    [
      ...agentSidebarConversationKeys.all,
      "project",
      projectId ?? "",
      "archived",
      archivedOnly,
      "search",
      search.trim().toLowerCase(),
      "states",
      publicationStates,
      "pinned",
      pinnedConversationIds,
      "priority",
      priorityConversationIds,
    ] as const,
  automationIndex: (
    projectIds: string[],
    archivedOnly: boolean,
    search = "",
    publicationStates: AgentSidebarPublicationState[] = [],
    pinnedConversationIds: string[] = [],
    priorityConversationIds: string[] = [],
    sort: AgentSidebarSort = "latest"
  ) =>
    [
      ...agentSidebarConversationKeys.all,
      "automation",
      "index",
      "projects",
      projectIds,
      "archived",
      archivedOnly,
      "search",
      search.trim().toLowerCase(),
      "states",
      publicationStates,
      "pinned",
      pinnedConversationIds,
      "priority",
      priorityConversationIds,
      "sort",
      sort,
    ] as const,
  automationGroup: (
    groupKey: string,
    projectIds: string[],
    archivedOnly: boolean,
    search = "",
    publicationStates: AgentSidebarPublicationState[] = [],
    pinnedConversationIds: string[] = [],
    priorityConversationIds: string[] = [],
    sort: AgentSidebarSort = "latest"
  ) =>
    [
      ...agentSidebarConversationKeys.all,
      "automation",
      groupKey,
      "projects",
      projectIds,
      "archived",
      archivedOnly,
      "search",
      search.trim().toLowerCase(),
      "states",
      publicationStates,
      "pinned",
      pinnedConversationIds,
      "priority",
      priorityConversationIds,
      "sort",
      sort,
    ] as const,
};
