// GENERATED — do not edit; run node scripts/check-agent-control-command-mirror.mjs --update

/** `schemaVersion` of the manifest this mirror was generated from. */
export const REMOTE_MANIFEST_SCHEMA_VERSION = 2;

/** Scope class a remotely-reachable operation is served under. */
export type RemoteOpClass = "read" | "operate" | "agentControl";

export interface RemoteFacadePin {
  readonly param: string;
  readonly field: string;
  readonly value: unknown;
}

export interface RemoteFacadeOp {
  readonly opClass: RemoteOpClass;
  /** The host inspects arguments to decide the effective class (see conditionals). */
  readonly argumentSensitive: boolean;
  readonly capabilities: readonly string[];
  /** Argument values the facade pins, e.g. `decision: "deny"`. */
  readonly pins: readonly RemoteFacadePin[];
}

/**
 * Every operation the host facade exposes remotely. A command ABSENT from this map is
 * not reachable remotely at all — no scope grant changes that.
 */
export const REMOTE_FACADE_OPS: Readonly<Record<string, RemoteFacadeOp>> = {
  "activate_methodology": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "add_artifact_relation": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["mutatesAgentConsumedContent"],
    pins: [],
  },
  "answer_user_question": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "approve_fix_task": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "approve_permission_request": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [{"param":"args","field":"decision","value":"allow"}],
  },
  "approve_persona": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["mutatesAgentConsumedContent"],
    pins: [],
  },
  "approve_persona_as_new": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["mutatesAgentConsumedContent"],
    pins: [],
  },
  "approve_review": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["mutatesAgentConsumedContent"],
    pins: [],
  },
  "approve_task_for_review": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["mutatesAgentConsumedContent"],
    pins: [],
  },
  "archive_artifact": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["mutatesAgentConsumedContent"],
    pins: [],
  },
  "archive_persona": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["mutatesAgentConsumedContent"],
    pins: [],
  },
  "archive_task": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "assess_all_priorities": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "assess_proposal_priority": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "block_task": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "cancel_automation_run": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "cancel_tasks_in_group": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "clear_active_plan": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "clear_mcp_server_override": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "clear_mcp_tool_override": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "count_session_activity_events": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "count_task_activity_events": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "create_agent_conversation": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "create_artifact": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["mutatesAgentConsumedContent"],
    pins: [],
  },
  "create_bucket": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "create_persona_draft": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["mutatesAgentConsumedContent"],
    pins: [],
  },
  "create_task": {
    opClass: "operate",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "create_task_step": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["mutatesAgentConsumedContent"],
    pins: [],
  },
  "create_workflow": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "deactivate_methodology": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "deny_permission_request": {
    opClass: "operate",
    argumentSensitive: false,
    capabilities: [],
    pins: [{"param":"args","field":"decision","value":"deny"}],
  },
  "finalize_automation": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["seedsSpawnTriggeringState"],
    pins: [],
  },
  "get_active_execution_plan": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_active_methodology": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_active_plan": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_active_project": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_active_workflow_columns": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_agent_conversation_role_default": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_agent_conversation_runtime_index": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_agent_conversation_stats": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_agent_conversation_summary": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_agent_lane_settings": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_archived_count": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_artifact": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_artifact_at_version": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_artifact_full": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_artifact_relations": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_artifact_version": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_artifact_version_history": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_artifacts": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_artifacts_by_bucket": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_artifacts_by_task": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_automation": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_blocked_tasks": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_buckets": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_builtin_workflows": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_bulk_workspace_publication_states": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_child_sessions": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_current_release_notes": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_execution_settings": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_fix_task_attempts": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_global_execution_settings": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_ideation_agent_workspace": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_ideation_effort_settings": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_ideation_model_settings": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_ideation_session": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_ideation_session_with_data": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_ideation_settings": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_insights_chat_usage_stats": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_insights_pr_insights": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_insights_stats": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_insights_trends": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_issue_progress": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_last_seen_release_notes_version": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_latest_child_session_id": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_merge_phase_list": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_merge_pipeline": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_merge_progress": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_methodologies": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_metrics_config": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_notification_settings": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_pending_reviews": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_persona": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_project_chat_usage_stats": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_project_pr_insights": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_project_stats": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_project_trends": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_proposal_dependencies": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_proposal_dependents": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_qa_results": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_qa_settings": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_related_artifacts": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_release_notes_for_version": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_remote_agent_conversation": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_remote_agent_conversation_messages_page": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_remote_agent_conversation_timeline_page": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_remote_provider_readiness": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_research_presets": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_research_process": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_research_processes": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_review_by_id": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_review_settings": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_reviews_by_task_id": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_session_group_counts": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_session_task_history_availability": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_start_composer_role_default": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_step_progress": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_system_buckets": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_task": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_task_agent_workspace": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_task_blockers": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_task_chat_usage_stats": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_task_context": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_task_dependency_graph": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_task_issues": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_task_metrics": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_task_proposal": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_task_qa": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_task_state_history": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_task_state_transitions": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_task_steps": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_task_timeline_events": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_tasks_awaiting_review": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_tasks_disable_impact": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_ui_feature_flags": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_unread_notification_count": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_update_channel": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_valid_transitions": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_workflow": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_workflows": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "get_workspace_review_runtime_settings": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "health_check": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "inject_task": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["seedsSpawnTriggeringState"],
    pins: [],
  },
  "list_agent_conversation_workspace_publication_events": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "list_agent_models": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "list_all_activity_events": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "list_attention_items": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "list_automations": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "list_ideation_sessions": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "list_notifications": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "list_pending_permission_gates": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "list_pending_question_gates": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "list_persona_usage": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "list_personas": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "list_plan_selector_candidates": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "list_release_notes_versions": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "list_remote_agent_conversations": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "list_remote_agent_conversations_page": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "list_remote_agent_sidebar_conversations": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "list_remote_projects": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "list_session_activity_events": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "list_session_proposals": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "list_sessions_by_group": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "list_task_activity_events": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "list_tasks": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "mark_all_notifications_read": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "mark_issue_addressed": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl","mutatesAgentConsumedContent"],
    pins: [],
  },
  "mark_issue_in_progress": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl","mutatesAgentConsumedContent"],
    pins: [],
  },
  "mark_notification_read": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "mark_release_notes_seen": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "move_task": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl","mutatesAgentConsumedContent"],
    pins: [],
  },
  "pause_automation": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "pause_execution": {
    opClass: "operate",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "pause_research": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "pause_task": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "pause_tasks_in_group": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "preview_persona_overlay": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "re_review_task_from_escalated": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "reanalyze_project": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "reject_review": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["mutatesAgentConsumedContent"],
    pins: [],
  },
  "remove_proposal_dependency": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "reopen_issue": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl","mutatesAgentConsumedContent"],
    pins: [],
  },
  "reorder_proposals": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "request_changes": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["mutatesAgentConsumedContent"],
    pins: [],
  },
  "request_task_changes_for_review": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["mutatesAgentConsumedContent"],
    pins: [],
  },
  "reseed_persona_draft": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["mutatesAgentConsumedContent"],
    pins: [],
  },
  "restart_automation": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "restore_agent_conversation": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "restore_task": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "resume_automation": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["seedsSpawnTriggeringState"],
    pins: [],
  },
  "resume_automation_run": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["seedsSpawnTriggeringState"],
    pins: [],
  },
  "resume_research": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "retry_automation_plan_judge": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "retry_qa": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "save_metrics_config": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "search_agent_composer_plan_references": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "search_artifacts": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "search_tasks": {
    opClass: "read",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "seed_builtin_workflows": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "send_remote_chat_message": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["mutatesAgentConsumedContent"],
    pins: [{"param":"input","field":"role","value":"user"}],
  },
  "set_active_project": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "set_default_workflow": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "set_dock_badge_count": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "skip_automation_judge": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "start_research": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "stop_automation": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "stop_execution": {
    opClass: "operate",
    argumentSensitive: false,
    capabilities: [],
    pins: [],
  },
  "stop_research": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "stop_task": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "unarchive_persona": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["mutatesAgentConsumedContent"],
    pins: [],
  },
  "unblock_task": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "update_agent_conversation_title": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "update_agent_lane_settings": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "update_artifact": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["mutatesAgentConsumedContent"],
    pins: [],
  },
  "update_automation_settings": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "update_ideation_effort_settings": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "update_ideation_model_settings": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "update_ideation_session_title": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "update_ideation_settings": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "update_mcp_server_override": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "update_mcp_tool_override": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "update_notification_settings": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "update_persona": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["mutatesAgentConsumedContent"],
    pins: [],
  },
  "update_persona_draft": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["mutatesAgentConsumedContent"],
    pins: [],
  },
  "update_qa_settings": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "update_remote_execution_settings": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "update_review_settings": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl","seedsSpawnTriggeringState"],
    pins: [],
  },
  "update_task": {
    opClass: "operate",
    argumentSensitive: true,
    capabilities: [],
    pins: [],
  },
  "update_task_proposal": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["mutatesAgentConsumedContent"],
    pins: [],
  },
  "update_task_step": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["mutatesAgentConsumedContent"],
    pins: [],
  },
  "update_ui_feature_flags": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "update_workflow": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "update_workspace_review_runtime_settings": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "upsert_custom_agent_model": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl"],
    pins: [],
  },
  "verify_issue": {
    opClass: "agentControl",
    argumentSensitive: false,
    capabilities: ["agentControl","mutatesAgentConsumedContent"],
    pins: [],
  },
};

export interface RemoteConditionalCapability {
  readonly capability: string;
  /** Argument fields that escalate the op's effective class to `agentControl`. */
  readonly fields: readonly string[];
}

/** Ops whose required scope depends on WHICH fields the caller is changing. */
export const REMOTE_CONDITIONAL_CAPABILITIES: Readonly<
  Record<string, RemoteConditionalCapability>
> = {
  "update_task": {
    capability: "mutatesAgentConsumedContent",
    fields: ["title","description"],
  },
};
