use super::agent_workspace_pr_metadata_reconciliation::*;
use std::sync::Arc;

use crate::application::agent_workspace_pr_description::ExistingPrMetadataSnapshot;
use crate::domain::entities::{
    AgentConversationWorkspace, AgentConversationWorkspaceMode, AgentWorkspacePrMetadataDecision,
    AgentWorkspacePublicationMetadataPhase, AgentWorkspacePublicationMetadataState,
    ChatConversation, IdeationAnalysisBaseRefKind, ProjectId,
};
use crate::domain::repositories::AgentConversationWorkspaceRepository;
use crate::domain::services::github_service::{PrDetail, PrStatus};
use crate::domain::services::GithubServiceTrait;
use crate::error::AppError;
use crate::infrastructure::memory::MemoryAgentConversationWorkspaceRepository;
use crate::tests::mock_github_service::MockGithubService;

const PR_NUMBER: i64 = 77;

fn pr_detail(title: &str, body: Option<&str>) -> PrDetail {
    PrDetail {
        number: PR_NUMBER,
        title: title.to_string(),
        body: body.map(str::to_string),
        author: Some("ralphx".to_string()),
        created_at: None,
        url: Some("https://github.test/pr/77".to_string()),
        state: PrStatus::Open,
        is_draft: false,
        head_ref_name: "feature/metadata".to_string(),
        base_ref_name: "main".to_string(),
    }
}

fn conversation_and_snapshot() -> (ChatConversation, ExistingPrMetadataSnapshot) {
    let project_id = ProjectId::from_string("metadata-reconciliation".to_string());
    let mut conversation = ChatConversation::new_project(project_id);
    conversation.title = Some("RX-42: Metadata reconciliation".to_string());
    let body = "## Before\n\n<!-- ralphx:managed-pr-body:start -->\n---\n\n_Generated by [RalphX](https://github.com/aigentive/ralphx.app)_\n<!-- ralphx:managed-pr-body:end -->";
    (
        conversation,
        ExistingPrMetadataSnapshot::from_detail(pr_detail("Before title", Some(body))),
    )
}

async fn repository_for(
    conversation: &ChatConversation,
) -> Arc<dyn AgentConversationWorkspaceRepository> {
    let repository = Arc::new(MemoryAgentConversationWorkspaceRepository::new());
    let mut workspace = AgentConversationWorkspace::new(
        conversation.id.clone(),
        ProjectId::from_string(conversation.context_id.clone()),
        AgentConversationWorkspaceMode::Edit,
        IdeationAnalysisBaseRefKind::ProjectDefault,
        "main".to_string(),
        Some("main".to_string()),
        Some("0".repeat(40)),
        "feature/metadata".to_string(),
        "/tmp/metadata-reconciliation".to_string(),
    );
    workspace.publication_pr_number = Some(PR_NUMBER);
    workspace.publication_pr_url = Some("https://github.test/pr/77".to_string());
    workspace.publication_pr_status = Some("open".to_string());
    repository.create_or_update(workspace).await.unwrap();
    repository
}

fn patch_decision() -> AgentWorkspacePrMetadataDecision {
    AgentWorkspacePrMetadataDecision::patch(
        Some("Updated title".to_string()),
        Some("## Updated body".to_string()),
    )
    .unwrap()
}

#[tokio::test]
async fn prepare_persists_exact_hash_evidence_and_recomposed_patch() {
    let (conversation, snapshot) = conversation_and_snapshot();
    let repository = repository_for(&conversation).await;
    let github: Arc<dyn GithubServiceTrait> = Arc::new(MockGithubService::new());
    let service = AgentWorkspacePrMetadataReconciliationService::new(&repository, &github)
        .with_plan_markdown("## Plan".to_string());

    let prepared = service
        .prepare(&conversation, &snapshot, &patch_decision())
        .await
        .unwrap();

    assert_eq!(prepared.patch.target_pr_number, PR_NUMBER);
    assert_eq!(
        prepared.patch.requested_title.as_deref(),
        Some("RX-42: Updated title")
    );
    assert!(prepared
        .patch
        .requested_body
        .as_deref()
        .unwrap()
        .starts_with("## Updated body"));
    assert_eq!(prepared.receipt.before_title_sha256, sha256("Before title"));
    assert_eq!(
        prepared.receipt.intended_title_sha256.as_deref().unwrap(),
        sha256("RX-42: Updated title")
    );
    assert_eq!(
        prepared
            .receipt
            .intended_editable_body_sha256
            .as_deref()
            .unwrap(),
        sha256("## Updated body")
    );
    assert_eq!(
        repository
            .get_publication_metadata_receipt(&conversation.id)
            .await
            .unwrap(),
        Some(prepared.receipt)
    );
}

#[tokio::test]
async fn execute_success_mutates_once_and_settles_applied() {
    let (conversation, snapshot) = conversation_and_snapshot();
    let repository = repository_for(&conversation).await;
    let github = Arc::new(MockGithubService::new());
    let github_trait: Arc<dyn GithubServiceTrait> = github.clone();
    let service = AgentWorkspacePrMetadataReconciliationService::new(&repository, &github_trait);
    let prepared = service
        .prepare(&conversation, &snapshot, &patch_decision())
        .await
        .unwrap();
    let worktree = tempfile::tempdir().unwrap();

    assert_eq!(
        service
            .execute(worktree.path(), &conversation.id, &prepared)
            .await
            .unwrap(),
        AgentWorkspacePrMetadataReconciliationOutcome::Applied
    );
    assert_eq!(github.state().patch_pr_metadata_calls, 1);
    let receipt = repository
        .get_publication_metadata_receipt(&conversation.id)
        .await
        .unwrap()
        .unwrap();
    assert_eq!(
        receipt.phase,
        AgentWorkspacePublicationMetadataPhase::Settled
    );
    assert_eq!(
        receipt.state,
        AgentWorkspacePublicationMetadataState::Applied
    );
    let workspace = repository
        .get_by_conversation_id(&conversation.id)
        .await
        .unwrap()
        .unwrap();
    assert_eq!(
        workspace.publication_pr_url.as_deref(),
        Some("https://github.test/pr/77")
    );
    assert_eq!(workspace.publication_pr_status.as_deref(), Some("open"));
    assert_eq!(workspace.publication_push_status.as_deref(), Some("pushed"));
}

#[tokio::test]
async fn mutation_error_reconciles_an_applied_readback_without_retrying() {
    let (conversation, snapshot) = conversation_and_snapshot();
    let repository = repository_for(&conversation).await;
    let github = Arc::new(MockGithubService::new());
    github.state().patch_pr_metadata_result =
        Some(Err(AppError::Infrastructure("timeout".to_string())));
    let github_trait: Arc<dyn GithubServiceTrait> = github.clone();
    let service = AgentWorkspacePrMetadataReconciliationService::new(&repository, &github_trait);
    let prepared = service
        .prepare(&conversation, &snapshot, &patch_decision())
        .await
        .unwrap();
    github.queue_pr_detail(Ok(pr_detail(
        prepared.patch.requested_title.as_deref().unwrap(),
        prepared.patch.requested_body.as_deref(),
    )));
    let worktree = tempfile::tempdir().unwrap();

    assert_eq!(
        service
            .execute(worktree.path(), &conversation.id, &prepared)
            .await
            .unwrap(),
        AgentWorkspacePrMetadataReconciliationOutcome::Reconciled
    );
    let state = github.state();
    assert_eq!(state.patch_pr_metadata_calls, 1);
    assert_eq!(state.fetch_pr_detail_calls, 1);
}

#[tokio::test]
async fn mutation_error_with_unchanged_remote_settles_not_applied() {
    let (conversation, snapshot) = conversation_and_snapshot();
    let repository = repository_for(&conversation).await;
    let github = Arc::new(MockGithubService::new());
    github.state().patch_pr_metadata_result =
        Some(Err(AppError::Infrastructure("timeout".to_string())));
    github.queue_pr_detail(Ok(pr_detail(&snapshot.title, snapshot.body.as_deref())));
    let github_trait: Arc<dyn GithubServiceTrait> = github.clone();
    let service = AgentWorkspacePrMetadataReconciliationService::new(&repository, &github_trait);
    let prepared = service
        .prepare(&conversation, &snapshot, &patch_decision())
        .await
        .unwrap();
    let worktree = tempfile::tempdir().unwrap();

    assert_eq!(
        service
            .execute(worktree.path(), &conversation.id, &prepared)
            .await
            .unwrap(),
        AgentWorkspacePrMetadataReconciliationOutcome::NotApplied
    );
    assert_eq!(github.state().patch_pr_metadata_calls, 1);
    assert_eq!(
        repository
            .get_by_conversation_id(&conversation.id)
            .await
            .unwrap()
            .unwrap()
            .publication_push_status
            .as_deref(),
        Some("description_failed")
    );
}

#[tokio::test]
async fn readback_classification_rejects_mixed_and_lost_managed_boundaries() {
    let (conversation, snapshot) = conversation_and_snapshot();
    let repository = repository_for(&conversation).await;
    let github: Arc<dyn GithubServiceTrait> = Arc::new(MockGithubService::new());
    let service = AgentWorkspacePrMetadataReconciliationService::new(&repository, &github);
    let prepared = service
        .prepare(&conversation, &snapshot, &patch_decision())
        .await
        .unwrap();

    assert_eq!(
        classify_readback(
            &prepared.receipt,
            &pr_detail(
                prepared.patch.requested_title.as_deref().unwrap(),
                snapshot.body.as_deref()
            )
        ),
        AgentWorkspacePrMetadataReadbackClassification::Conflicted
    );
    assert_eq!(
        classify_readback(
            &prepared.receipt,
            &pr_detail(
                prepared.patch.requested_title.as_deref().unwrap(),
                Some("## Updated body")
            )
        ),
        AgentWorkspacePrMetadataReadbackClassification::Conflicted
    );
}

#[tokio::test]
async fn readback_allows_valid_suffix_only_change_when_editable_prefix_matches() {
    let (conversation, snapshot) = conversation_and_snapshot();
    let repository = repository_for(&conversation).await;
    let github: Arc<dyn GithubServiceTrait> = Arc::new(MockGithubService::new());
    let service = AgentWorkspacePrMetadataReconciliationService::new(&repository, &github);
    let prepared = service
        .prepare(&conversation, &snapshot, &patch_decision())
        .await
        .unwrap();
    let body = "## Updated body\n\n<!-- ralphx:managed-pr-body:start -->\n---\n\n_Generated by [RalphX](https://github.com/aigentive/ralphx.app)_\nextra suffix\n<!-- ralphx:managed-pr-body:end -->".to_string();

    assert_eq!(
        classify_readback(
            &prepared.receipt,
            &pr_detail(
                prepared.patch.requested_title.as_deref().unwrap(),
                Some(&body)
            )
        ),
        AgentWorkspacePrMetadataReadbackClassification::Applied
    );
}

#[tokio::test]
async fn readback_rejects_concurrent_drift_in_an_unrequested_editable_field() {
    let (conversation, snapshot) = conversation_and_snapshot();
    let repository = repository_for(&conversation).await;
    let github: Arc<dyn GithubServiceTrait> = Arc::new(MockGithubService::new());
    let service = AgentWorkspacePrMetadataReconciliationService::new(&repository, &github);

    let title_only = service
        .prepare(
            &conversation,
            &snapshot,
            &AgentWorkspacePrMetadataDecision::patch(Some("Updated title".to_string()), None)
                .unwrap(),
        )
        .await
        .unwrap();
    assert_eq!(
        classify_readback(
            &title_only.receipt,
            &pr_detail(
                title_only.patch.requested_title.as_deref().unwrap(),
                Some("Concurrent editable body")
            )
        ),
        AgentWorkspacePrMetadataReadbackClassification::Conflicted
    );

    let second_conversation = {
        let mut value = conversation.clone();
        value.id = crate::domain::entities::ChatConversationId::new();
        value
    };
    let second_repository = repository_for(&second_conversation).await;
    let second_service =
        AgentWorkspacePrMetadataReconciliationService::new(&second_repository, &github);
    let body_only = second_service
        .prepare(
            &second_conversation,
            &snapshot,
            &AgentWorkspacePrMetadataDecision::patch(None, Some("## Updated body".to_string()))
                .unwrap(),
        )
        .await
        .unwrap();
    assert_eq!(
        classify_readback(
            &body_only.receipt,
            &pr_detail(
                "Concurrent title",
                body_only.patch.requested_body.as_deref()
            )
        ),
        AgentWorkspacePrMetadataReadbackClassification::Conflicted
    );
}

#[tokio::test]
async fn unreadable_post_mutation_remote_stays_reconciling_unknown() {
    let (conversation, snapshot) = conversation_and_snapshot();
    let repository = repository_for(&conversation).await;
    let github = Arc::new(MockGithubService::new());
    github.state().patch_pr_metadata_result =
        Some(Err(AppError::Infrastructure("timeout".to_string())));
    github.will_fail_pr_detail("unavailable");
    let github_trait: Arc<dyn GithubServiceTrait> = github.clone();
    let service = AgentWorkspacePrMetadataReconciliationService::new(&repository, &github_trait);
    let prepared = service
        .prepare(&conversation, &snapshot, &patch_decision())
        .await
        .unwrap();
    let worktree = tempfile::tempdir().unwrap();

    assert_eq!(
        service
            .execute(worktree.path(), &conversation.id, &prepared)
            .await
            .unwrap(),
        AgentWorkspacePrMetadataReconciliationOutcome::Unknown
    );
    let receipt = repository
        .get_publication_metadata_receipt(&conversation.id)
        .await
        .unwrap()
        .unwrap();
    assert_eq!(
        receipt.phase,
        AgentWorkspacePublicationMetadataPhase::Reconciling
    );
    assert_eq!(
        receipt.state,
        AgentWorkspacePublicationMetadataState::Unknown
    );
}

#[tokio::test]
async fn prepared_recovery_settles_not_attempted_without_remote_read() {
    let (conversation, snapshot) = conversation_and_snapshot();
    let repository = repository_for(&conversation).await;
    let github = Arc::new(MockGithubService::new());
    let github_trait: Arc<dyn GithubServiceTrait> = github.clone();
    let service = AgentWorkspacePrMetadataReconciliationService::new(&repository, &github_trait);
    service
        .prepare(&conversation, &snapshot, &patch_decision())
        .await
        .unwrap();
    let worktree = tempfile::tempdir().unwrap();

    assert_eq!(
        service
            .recover(worktree.path(), &conversation.id)
            .await
            .unwrap(),
        Some(AgentWorkspacePrMetadataReconciliationOutcome::NotAttempted)
    );
    assert_eq!(github.state().fetch_pr_detail_calls, 0);
    assert_eq!(
        repository
            .get_by_conversation_id(&conversation.id)
            .await
            .unwrap()
            .unwrap()
            .publication_push_status
            .as_deref(),
        Some("description_failed")
    );
}

#[tokio::test]
async fn one_redraft_refresh_rebinds_authority_and_stale_refresh_has_no_side_effects() {
    let (conversation, snapshot) = conversation_and_snapshot();
    let repository = repository_for(&conversation).await;
    let github = Arc::new(MockGithubService::new());
    let github_trait: Arc<dyn GithubServiceTrait> = github.clone();
    let service = AgentWorkspacePrMetadataReconciliationService::new(&repository, &github_trait);
    let prepared = service
        .prepare(&conversation, &snapshot, &patch_decision())
        .await
        .unwrap();
    let refreshed_snapshot = ExistingPrMetadataSnapshot::from_detail(pr_detail(
        "Concurrent title",
        Some(
            "## Concurrent body\n\n<!-- ralphx:managed-pr-body:start -->\n---\n\n_Generated by [RalphX](https://github.com/aigentive/ralphx.app)_\n<!-- ralphx:managed-pr-body:end -->",
        ),
    ));
    let refreshed_decision = AgentWorkspacePrMetadataDecision::patch(
        Some("Redrafted title".to_string()),
        Some("## Redrafted body".to_string()),
    )
    .unwrap();

    let refreshed = service
        .refresh_prepared(
            &conversation,
            &refreshed_snapshot,
            &refreshed_decision,
            &prepared,
        )
        .await
        .unwrap()
        .expect("current prepared attempt should refresh");
    assert_eq!(refreshed.receipt.attempt_id, prepared.receipt.attempt_id);
    assert_ne!(
        refreshed.receipt.before_authority_sha256,
        prepared.receipt.before_authority_sha256
    );
    assert_eq!(
        repository
            .get_publication_metadata_receipt(&conversation.id)
            .await
            .unwrap(),
        Some(refreshed.receipt.clone())
    );
    assert_eq!(
        repository
            .get_pr_metadata_decision(&conversation.id)
            .await
            .unwrap(),
        Some(refreshed.patch.normalized_decision.clone())
    );

    let worktree = tempfile::tempdir().unwrap();
    assert_eq!(
        service
            .execute(worktree.path(), &conversation.id, &refreshed)
            .await
            .unwrap(),
        AgentWorkspacePrMetadataReconciliationOutcome::Applied
    );
    let receipt_before_stale_refresh = repository
        .get_publication_metadata_receipt(&conversation.id)
        .await
        .unwrap();
    let events_before_stale_refresh = repository
        .list_publication_events(&conversation.id)
        .await
        .unwrap();
    assert!(service
        .refresh_prepared(
            &conversation,
            &refreshed_snapshot,
            &refreshed_decision,
            &prepared,
        )
        .await
        .unwrap()
        .is_none());
    assert_eq!(
        repository
            .get_publication_metadata_receipt(&conversation.id)
            .await
            .unwrap(),
        receipt_before_stale_refresh
    );
    assert_eq!(
        repository
            .list_publication_events(&conversation.id)
            .await
            .unwrap(),
        events_before_stale_refresh
    );
    assert_eq!(github.state().patch_pr_metadata_calls, 1);
}
