use super::*;

#[test]
fn appends_canonical_ralphx_footer() {
    assert_eq!(
        append_ralphx_generated_footer("## Review\n\nLooks good."),
        "## Review\n\nLooks good.\n\n---\n\n_Generated by [RalphX](https://github.com/aigentive/ralphx.app)_"
    );
}

#[test]
fn trims_trailing_whitespace_before_footer() {
    assert_eq!(
        append_ralphx_generated_footer("Review body.  \n\n"),
        "Review body.\n\n---\n\n_Generated by [RalphX](https://github.com/aigentive/ralphx.app)_"
    );
}

#[test]
fn preserves_an_already_signed_body_without_duplication() {
    let signed = format!("Review body.\n\n{RALPHX_GENERATED_FOOTER}\n\n");

    let result = append_ralphx_generated_footer(&signed);

    assert_eq!(result, signed.trim_end());
    assert_eq!(result.matches(RALPHX_GENERATED_FOOTER).count(), 1);
}

#[test]
fn splits_a_marked_managed_pr_body_and_preserves_every_suffix_byte() {
    let body = format!(
        "## Summary\n\nReviewer text\n\n{RALPHX_MANAGED_PR_BODY_START}\n\
         <details>\n<summary>View full plan</summary>\n\nPlan\n</details>\n\n\
         {RALPHX_GENERATED_FOOTER}\n{RALPHX_MANAGED_PR_BODY_END}\n\n\
         <!-- codesmith -->\nOpaque integration tail"
    );

    let decomposition = decompose_ralphx_managed_pr_body(&body);

    assert_eq!(decomposition.editable_prefix, "## Summary\n\nReviewer text");
    let preserved_suffix = decomposition
        .preserved_suffix
        .expect("marked body should preserve its managed suffix");
    assert_eq!(
        format!("{}{}", decomposition.editable_prefix, preserved_suffix),
        body
    );
    assert!(preserved_suffix.ends_with("<!-- codesmith -->\nOpaque integration tail"));
}

#[test]
fn splits_legacy_plan_signature_with_nested_details_and_trailing_content() {
    let body = format!(
        "Editable description\n\n<details>\n<summary>View full plan</summary>\n\n\
         Plan\n<details>\n<summary>Nested</summary>\nNested body\n</details>\n\
         </details>\n\n{RALPHX_GENERATED_FOOTER}\n\nThird-party tail"
    );

    let decomposition = decompose_ralphx_managed_pr_body(&body);

    assert_eq!(decomposition.editable_prefix, "Editable description");
    assert_eq!(
        format!(
            "{}{}",
            decomposition.editable_prefix,
            decomposition.preserved_suffix.unwrap()
        ),
        body
    );
}

#[test]
fn splits_a_legacy_signature_only_body() {
    let body = format!("Editable description\n\n{RALPHX_GENERATED_FOOTER}");

    let decomposition = decompose_ralphx_managed_pr_body(&body);

    assert_eq!(decomposition.editable_prefix, "Editable description");
    let expected_suffix = format!("\n\n{RALPHX_GENERATED_FOOTER}");
    assert_eq!(
        decomposition.preserved_suffix,
        Some(expected_suffix.as_str())
    );
}

#[test]
fn malformed_or_ambiguous_managed_tokens_leave_the_whole_body_editable() {
    let cases = [
        format!("Body\n\n{RALPHX_MANAGED_PR_BODY_START}\nunterminated"),
        format!(
            "Body\n\n{RALPHX_MANAGED_PR_BODY_START}\n{RALPHX_GENERATED_FOOTER}\n\
             {RALPHX_MANAGED_PR_BODY_END}\n{RALPHX_MANAGED_PR_BODY_END}"
        ),
        format!("Body\n\n{RALPHX_GENERATED_FOOTER}\n\n{RALPHX_GENERATED_FOOTER}"),
        format!(
            "Body\n\n<details>\n<summary>View full plan</summary>\nPlan\n\
             {RALPHX_GENERATED_FOOTER}"
        ),
    ];

    for body in cases {
        let decomposition = decompose_ralphx_managed_pr_body(&body);
        assert_eq!(decomposition.editable_prefix, body);
        assert_eq!(decomposition.preserved_suffix, None);
    }
}

#[test]
fn generic_generated_footer_output_does_not_gain_pr_body_markers() {
    let result = append_ralphx_generated_footer("Review body");

    assert!(!result.contains(RALPHX_MANAGED_PR_BODY_START));
    assert!(!result.contains(RALPHX_MANAGED_PR_BODY_END));
}
