/// Canonical footer attached to GitHub Markdown generated by RalphX.
pub(crate) const RALPHX_GENERATED_FOOTER: &str =
    "---\n\n_Generated by [RalphX](https://github.com/aigentive/ralphx.app)_";

/// Appends the canonical RalphX footer while avoiding an exact duplicate suffix.
pub(crate) fn append_ralphx_generated_footer(markdown: &str) -> String {
    let markdown = markdown.trim_end();
    if markdown.ends_with(RALPHX_GENERATED_FOOTER) {
        markdown.to_string()
    } else {
        format!("{markdown}\n\n{RALPHX_GENERATED_FOOTER}")
    }
}

#[cfg(test)]
#[path = "github_generated_markdown_tests.rs"]
mod tests;
