use super::*;

#[test]
fn appends_canonical_ralphx_footer() {
    assert_eq!(
        append_ralphx_generated_footer("## Review\n\nLooks good."),
        "## Review\n\nLooks good.\n\n---\n\n_Generated by [RalphX](https://github.com/aigentive/ralphx.app)_"
    );
}

#[test]
fn trims_trailing_whitespace_before_footer() {
    assert_eq!(
        append_ralphx_generated_footer("Review body.  \n\n"),
        "Review body.\n\n---\n\n_Generated by [RalphX](https://github.com/aigentive/ralphx.app)_"
    );
}

#[test]
fn preserves_an_already_signed_body_without_duplication() {
    let signed = format!("Review body.\n\n{RALPHX_GENERATED_FOOTER}\n\n");

    let result = append_ralphx_generated_footer(&signed);

    assert_eq!(result, signed.trim_end());
    assert_eq!(result.matches(RALPHX_GENERATED_FOOTER).count(), 1);
}
