/// Canonical footer attached to GitHub Markdown generated by RalphX.
pub(crate) const RALPHX_GENERATED_FOOTER: &str =
    "---\n\n_Generated by [RalphX](https://github.com/aigentive/ralphx.app)_";
pub(crate) const RALPHX_MANAGED_PR_BODY_START: &str = "<!-- ralphx:managed-pr-body:start -->";
pub(crate) const RALPHX_MANAGED_PR_BODY_END: &str = "<!-- ralphx:managed-pr-body:end -->";
pub(crate) const GITHUB_PR_BODY_SOFT_LIMIT_CHARS: usize = 60_000;
pub(crate) const PR_BODY_TRUNCATION_NOTICE: &str =
    "\n\n_Excerpt truncated by RalphX because GitHub PR descriptions have a body size limit._";

const PLAN_DETAILS_OPEN: &str = "<details>";
const PLAN_DETAILS_CLOSE: &str = "</details>";
const PLAN_SUMMARY: &str = "\n<summary>View full plan</summary>\n\n";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct RalphxManagedPrBody<'a> {
    pub(crate) editable_prefix: &'a str,
    pub(crate) preserved_suffix: Option<&'a str>,
}

/// Appends the canonical RalphX footer while avoiding an exact duplicate suffix.
pub(crate) fn append_ralphx_generated_footer(markdown: &str) -> String {
    let markdown = markdown.trim_end();
    if markdown.ends_with(RALPHX_GENERATED_FOOTER) {
        markdown.to_string()
    } else {
        format!("{markdown}\n\n{RALPHX_GENERATED_FOOTER}")
    }
}

pub(crate) fn decompose_ralphx_managed_pr_body(body: &str) -> RalphxManagedPrBody<'_> {
    let start_count = body.matches(RALPHX_MANAGED_PR_BODY_START).count();
    let end_count = body.matches(RALPHX_MANAGED_PR_BODY_END).count();
    if start_count > 0 || end_count > 0 {
        if start_count != 1 || end_count != 1 {
            return unrecognized(body);
        }
        let start = body
            .find(RALPHX_MANAGED_PR_BODY_START)
            .expect("single start marker must have an index");
        let end = body
            .find(RALPHX_MANAGED_PR_BODY_END)
            .expect("single end marker must have an index");
        if start >= end {
            return unrecognized(body);
        }
        let managed = &body[start + RALPHX_MANAGED_PR_BODY_START.len()..end];
        if managed.contains(RALPHX_MANAGED_PR_BODY_START)
            || managed.contains(RALPHX_MANAGED_PR_BODY_END)
            || managed.matches(RALPHX_GENERATED_FOOTER).count() != 1
        {
            return unrecognized(body);
        }
        return recognized(body, start);
    }

    if body.matches(RALPHX_GENERATED_FOOTER).count() != 1 {
        return unrecognized(body);
    }
    let signature_start = body
        .find(RALPHX_GENERATED_FOOTER)
        .expect("single canonical signature must have an index");
    if let Some(plan_start) = adjacent_legacy_plan_start(body, signature_start) {
        return recognized(body, plan_start);
    }
    if body[..signature_start].contains("<details>\n<summary>View full plan</summary>") {
        return unrecognized(body);
    }
    recognized(body, signature_start)
}

pub(crate) fn max_editable_chars_for_preserved_suffix(preserved_suffix: &str) -> Option<usize> {
    let suffix_chars = preserved_suffix.chars().count();
    if suffix_chars >= GITHUB_PR_BODY_SOFT_LIMIT_CHARS {
        None
    } else {
        Some(GITHUB_PR_BODY_SOFT_LIMIT_CHARS - suffix_chars)
    }
}

pub(crate) fn fit_editable_prefix_for_preserved_suffix(
    editable_prefix: &str,
    preserved_suffix: &str,
) -> Option<String> {
    let editable_prefix = editable_prefix.trim_end();
    let max_editable_chars = max_editable_chars_for_preserved_suffix(preserved_suffix)?;
    if editable_prefix.chars().count() <= max_editable_chars {
        return (!editable_prefix.trim().is_empty()).then(|| editable_prefix.to_string());
    }
    let notice_chars = PR_BODY_TRUNCATION_NOTICE.chars().count();
    if max_editable_chars <= notice_chars {
        return None;
    }
    let truncated = editable_prefix
        .chars()
        .take(max_editable_chars - notice_chars)
        .collect::<String>();
    (!truncated.trim().is_empty())
        .then(|| format!("{}{PR_BODY_TRUNCATION_NOTICE}", truncated.trim_end()))
}

fn adjacent_legacy_plan_start(body: &str, signature_start: usize) -> Option<usize> {
    let before_signature = &body[..signature_start];
    let close_end = before_signature.strip_suffix("\n\n")?.len();
    let close_start = close_end.checked_sub(PLAN_DETAILS_CLOSE.len())?;
    if &body[close_start..close_end] != PLAN_DETAILS_CLOSE {
        return None;
    }

    let mut stack = Vec::new();
    let mut cursor = 0;
    while cursor < close_end {
        let next_open = body[cursor..close_end]
            .find(PLAN_DETAILS_OPEN)
            .map(|offset| cursor + offset);
        let next_close = body[cursor..close_end]
            .find(PLAN_DETAILS_CLOSE)
            .map(|offset| cursor + offset);
        match (next_open, next_close) {
            (Some(open), Some(close)) if open < close => {
                stack.push(open);
                cursor = open + PLAN_DETAILS_OPEN.len();
            }
            (_, Some(close)) => {
                let open = stack.pop()?;
                if close == close_start {
                    if !stack.is_empty()
                        || !body[open + PLAN_DETAILS_OPEN.len()..].starts_with(PLAN_SUMMARY)
                    {
                        return None;
                    }
                    return Some(open);
                }
                cursor = close + PLAN_DETAILS_CLOSE.len();
            }
            (Some(open), None) => {
                stack.push(open);
                cursor = open + PLAN_DETAILS_OPEN.len();
            }
            (None, None) => break,
        }
    }
    None
}

fn recognized(body: &str, managed_start: usize) -> RalphxManagedPrBody<'_> {
    let suffix_start = body[..managed_start]
        .strip_suffix("\n\n")
        .map_or(managed_start, str::len);
    RalphxManagedPrBody {
        editable_prefix: &body[..suffix_start],
        preserved_suffix: Some(&body[suffix_start..]),
    }
}

fn unrecognized(body: &str) -> RalphxManagedPrBody<'_> {
    RalphxManagedPrBody {
        editable_prefix: body,
        preserved_suffix: None,
    }
}

#[cfg(test)]
#[path = "github_generated_markdown_tests.rs"]
mod tests;
