use super::*;

pub(super) fn build_agent_workspace_pr_title(conversation: &ChatConversation) -> String {
    conversation
        .title
        .as_deref()
        .map(str::trim)
        .filter(|value| !value.is_empty() && *value != "Untitled agent")
        .map(str::to_string)
        .unwrap_or_else(|| "Agent conversation changes".to_string())
}

pub(super) fn write_agent_workspace_pr_body(body: &str) -> AppResult<NamedTempFile> {
    let body_file = NamedTempFile::new().map_err(|e| {
        AppError::Infrastructure(format!("failed to create PR body temp file: {e}"))
    })?;
    use std::io::Write as _;
    (&body_file)
        .write_all(body.as_bytes())
        .map_err(|e| AppError::Infrastructure(format!("failed to write PR body temp file: {e}")))?;
    Ok(body_file)
}

pub(super) fn finalize_agent_workspace_pr_body(
    body: &str,
    plan_markdown: &Option<String>,
) -> String {
    let footer = format!(
        "\n\n---\n\n_Generated by [RalphX]({})_",
        RALPHX_REPOSITORY_URL
    );
    match plan_markdown {
        Some(plan) if !plan.trim().is_empty() => {
            let prefix = format!("{}\n\n", body.trim_end());
            let suffix = format!("\n\n</details>{footer}");
            let plan_header = "<details>\n<summary>View full plan</summary>\n\n";
            let full_prefix = format!("{prefix}{plan_header}");
            fit_plan_markdown_to_pr_body(&full_prefix, plan.trim(), &suffix)
        }
        _ => format!("{}{footer}", body.trim_end()),
    }
}

fn char_count(text: &str) -> usize {
    text.chars().count()
}

fn truncate_chars(text: &str, max_chars: usize) -> String {
    text.chars().take(max_chars).collect()
}

pub(super) fn fit_plan_markdown_to_pr_body(
    prefix: &str,
    plan_markdown: &str,
    suffix: &str,
) -> String {
    let full_body = format!("{prefix}{plan_markdown}{suffix}");
    if char_count(&full_body) <= GITHUB_PR_BODY_SOFT_LIMIT_CHARS {
        return full_body;
    }

    let fixed_chars =
        char_count(prefix) + char_count(suffix) + char_count(PR_BODY_TRUNCATION_NOTICE);
    if fixed_chars >= GITHUB_PR_BODY_SOFT_LIMIT_CHARS {
        return truncate_chars(&full_body, GITHUB_PR_BODY_SOFT_LIMIT_CHARS);
    }

    let available_plan_chars = GITHUB_PR_BODY_SOFT_LIMIT_CHARS - fixed_chars;
    let truncated_plan = truncate_chars(plan_markdown, available_plan_chars);
    format!(
        "{prefix}{}{}{suffix}",
        truncated_plan.trim_end(),
        PR_BODY_TRUNCATION_NOTICE
    )
}
