use super::*;

use crate::domain::entities::{
    AgentConversationWorkspaceMode, ArtifactId, IdeationAnalysisBaseRefKind, IdeationSessionId,
    ProjectId, TaskCategory,
};
use crate::tests::mock_github_service::MockGithubService;

fn agent_workspace_fixture() -> (ChatConversation, AgentConversationWorkspace) {
    let project_id = ProjectId::from_string("project-pr-publish".to_string());
    let mut conversation = ChatConversation::new_project(project_id.clone());
    conversation.title = Some("Conversation title".to_string());
    let workspace = AgentConversationWorkspace::new(
        conversation.id.clone(),
        project_id,
        AgentConversationWorkspaceMode::Edit,
        IdeationAnalysisBaseRefKind::ProjectDefault,
        "main".to_string(),
        Some("main".to_string()),
        Some("0".repeat(40)),
        "feature/pr-description".to_string(),
        "/tmp/pr-description-worktree".to_string(),
    );
    (conversation, workspace)
}

#[tokio::test]
async fn agent_workspace_publisher_creates_draft_with_generated_body() {
    let (conversation, workspace) = agent_workspace_fixture();
    let description = AgentWorkspacePrDescription::new(
        Some("Generated PR title".to_string()),
        "## Summary\n\nGenerated body".to_string(),
    );
    let github = Arc::new(MockGithubService::new());
    github.will_create_pr(42, "https://github.com/mock/repo/pull/42");
    let github_trait: Arc<dyn GithubServiceTrait> = github.clone();
    let publisher = AgentWorkspacePrPublisher::new(&github_trait);
    let temp_dir = tempfile::tempdir().unwrap();

    let outcome = publisher
        .publish_draft_pr(temp_dir.path(), &conversation, &workspace, &description)
        .await
        .unwrap();

    assert_eq!(outcome.pr_number, 42);
    assert!(outcome.created_pr);
    assert_eq!(outcome.pr_status, "draft");
    let state = github.state();
    let (base, head, title, body_path) = state
        .last_create_draft_pr_args
        .clone()
        .expect("draft PR args should be captured");
    assert_eq!(base, "main");
    assert_eq!(head, "feature/pr-description");
    assert_eq!(title, "Generated PR title");
    assert!(body_path.contains("tmp"));
    let body = state.last_create_draft_pr_body.as_deref().unwrap();
    assert!(body.starts_with("## Summary\n\nGenerated body"));
    assert!(body.contains("_Generated by [RalphX]("));
}

#[tokio::test]
async fn agent_workspace_publisher_updates_existing_pr_with_title_fallback() {
    let (mut conversation, mut workspace) = agent_workspace_fixture();
    conversation.title = Some("Untitled agent".to_string());
    workspace.publication_pr_number = Some(77);
    workspace.publication_pr_url = Some("https://github.com/mock/repo/pull/77".to_string());
    let description =
        AgentWorkspacePrDescription::new(None, "## Summary\n\nUpdated body".to_string());
    let github = Arc::new(MockGithubService::new());
    let github_trait: Arc<dyn GithubServiceTrait> = github.clone();
    let publisher = AgentWorkspacePrPublisher::new(&github_trait);
    let temp_dir = tempfile::tempdir().unwrap();

    let outcome = publisher
        .publish_draft_pr(temp_dir.path(), &conversation, &workspace, &description)
        .await
        .unwrap();

    assert_eq!(outcome.pr_number, 77);
    assert!(!outcome.created_pr);
    assert_eq!(outcome.pr_status, "open");
    assert_eq!(outcome.pr_url, "https://github.com/mock/repo/pull/77");
    let state = github.state();
    assert_eq!(state.update_pr_details_calls, 1);
    let (pr_number, title, body_path) = state
        .last_update_pr_details_args
        .clone()
        .expect("update PR args should be captured");
    assert_eq!(pr_number, 77);
    assert_eq!(title, "Agent conversation changes");
    assert!(body_path.contains("tmp"));
    let body = state.last_update_pr_details_body.as_deref().unwrap();
    assert!(body.starts_with("## Summary\n\nUpdated body"));
    assert!(body.contains("_Generated by [RalphX]("));
}

#[tokio::test]
async fn agent_workspace_publisher_prefixes_pr_title_with_jira_key() {
    let (mut conversation, workspace) = agent_workspace_fixture();
    conversation.title = Some("rx-42: Fix composer references".to_string());
    let description = AgentWorkspacePrDescription::new(
        Some("Fix composer references".to_string()),
        "## Summary\n\nGenerated body".to_string(),
    );
    let github = Arc::new(MockGithubService::new());
    github.will_create_pr(42, "https://github.com/mock/repo/pull/42");
    let github_trait: Arc<dyn GithubServiceTrait> = github.clone();
    let publisher = AgentWorkspacePrPublisher::new(&github_trait);
    let temp_dir = tempfile::tempdir().unwrap();

    let outcome = publisher
        .publish_draft_pr(temp_dir.path(), &conversation, &workspace, &description)
        .await
        .unwrap();

    assert_eq!(outcome.pr_number, 42);
    let state = github.state();
    let (_, _, title, _) = state
        .last_create_draft_pr_args
        .clone()
        .expect("draft PR args should be captured");
    assert_eq!(title, "RX-42: Fix composer references");
}

#[tokio::test]
async fn agent_workspace_publisher_forces_frozen_title_across_all_publish_outcomes() {
    let (conversation, workspace) = agent_workspace_fixture();
    let description = AgentWorkspacePrDescription::new(
        Some("Describer drift".to_string()),
        "## Summary\n\nGenerated body".to_string(),
    );
    let frozen_title = "ENG-42 - Frozen ticket title";

    let created = Arc::new(MockGithubService::new());
    created.will_create_pr(42, "https://github.com/mock/repo/pull/42");
    let created_trait: Arc<dyn GithubServiceTrait> = created.clone();
    AgentWorkspacePrPublisher::new(&created_trait)
        .with_frozen_title(frozen_title)
        .publish_draft_pr(
            tempfile::tempdir().unwrap().path(),
            &conversation,
            &workspace,
            &description,
        )
        .await
        .unwrap();
    assert_eq!(
        created
            .state()
            .last_create_draft_pr_args
            .as_ref()
            .unwrap()
            .2,
        frozen_title
    );

    let mut existing_workspace = workspace.clone();
    existing_workspace.publication_pr_number = Some(77);
    let updated = Arc::new(MockGithubService::new());
    let updated_trait: Arc<dyn GithubServiceTrait> = updated.clone();
    AgentWorkspacePrPublisher::new(&updated_trait)
        .with_frozen_title(frozen_title)
        .publish_draft_pr(
            tempfile::tempdir().unwrap().path(),
            &conversation,
            &existing_workspace,
            &description,
        )
        .await
        .unwrap();
    assert_eq!(
        updated
            .state()
            .last_update_pr_details_args
            .as_ref()
            .unwrap()
            .1,
        frozen_title
    );

    let duplicate = Arc::new(MockGithubService::new());
    duplicate.state().create_draft_pr_result = Some(Err(AppError::DuplicatePr));
    duplicate.set_find_pr_by_head_branch(Ok(Some((
        88,
        "https://github.com/mock/repo/pull/88".to_string(),
    ))));
    let duplicate_trait: Arc<dyn GithubServiceTrait> = duplicate.clone();
    AgentWorkspacePrPublisher::new(&duplicate_trait)
        .with_frozen_title(frozen_title)
        .publish_draft_pr(
            tempfile::tempdir().unwrap().path(),
            &conversation,
            &workspace,
            &description,
        )
        .await
        .unwrap();
    assert_eq!(
        duplicate
            .state()
            .last_update_pr_details_args
            .as_ref()
            .unwrap()
            .1,
        frozen_title
    );
}

#[tokio::test]
async fn agent_workspace_publisher_appends_plan_block_and_footer() {
    let (conversation, workspace) = agent_workspace_fixture();
    let description = AgentWorkspacePrDescription::new(
        Some("PR with plan".to_string()),
        "## Summary\n\nBody content".to_string(),
    );
    let github = Arc::new(MockGithubService::new());
    github.will_create_pr(99, "https://github.com/mock/repo/pull/99");
    let github_trait: Arc<dyn GithubServiceTrait> = github.clone();
    let publisher = AgentWorkspacePrPublisher::new(&github_trait)
        .with_plan_markdown("## Plan\n\nStep 1\nStep 2".to_string());
    let temp_dir = tempfile::tempdir().unwrap();

    publisher
        .publish_draft_pr(temp_dir.path(), &conversation, &workspace, &description)
        .await
        .unwrap();

    let state = github.state();
    let body = state.last_create_draft_pr_body.as_deref().unwrap();
    assert!(body.starts_with("## Summary\n\nBody content"));
    assert!(body.contains("<details>\n<summary>View full plan</summary>"));
    assert!(body.contains("## Plan\n\nStep 1\nStep 2"));
    assert!(body.contains("</details>"));
    assert!(body.contains("_Generated by [RalphX]("));
}

#[test]
fn finalized_pr_body_omits_empty_plan_and_keeps_footer() {
    let body = finalize_agent_workspace_pr_body(
        "## Summary\n\nBody content\n\n",
        &Some(" \n".to_string()),
    );

    assert_eq!(body.matches("<details>").count(), 0);
    assert!(body.starts_with("## Summary\n\nBody content"));
    assert!(body.contains("_Generated by [RalphX]("));
}

#[test]
fn finalized_pr_body_truncates_oversized_plan_inside_details() {
    let body = finalize_agent_workspace_pr_body(
        "## Summary",
        &Some("A".repeat(GITHUB_PR_BODY_SOFT_LIMIT_CHARS + 1024)),
    );

    assert_eq!(body.chars().count(), GITHUB_PR_BODY_SOFT_LIMIT_CHARS);
    assert!(body.starts_with("## Summary\n\n<details>"));
    assert!(body.contains("<summary>View full plan</summary>"));
    assert!(body.contains(PR_BODY_TRUNCATION_NOTICE));
    assert!(body.ends_with("_Generated by [RalphX](https://github.com/aigentive/ralphx.app)_"));
}

#[test]
fn fit_plan_markdown_truncates_raw_body_when_fixed_sections_exceed_limit() {
    let prefix = "P".repeat(GITHUB_PR_BODY_SOFT_LIMIT_CHARS);
    let body = fit_plan_markdown_to_pr_body(&prefix, "plan", "suffix");

    assert_eq!(body.chars().count(), GITHUB_PR_BODY_SOFT_LIMIT_CHARS);
    assert!(body.chars().all(|character| character == 'P'));
}

#[test]
fn pr_body_temp_file_contains_exact_markdown() {
    let body_file = write_agent_workspace_pr_body("## Summary\n\nExact body").unwrap();
    let body = std::fs::read_to_string(body_file.path()).unwrap();

    assert_eq!(body, "## Summary\n\nExact body");
}

#[tokio::test]
async fn plan_pr_publisher_uses_agent_body_and_ignores_repo_template() {
    let temp_dir = tempfile::tempdir().unwrap();
    let github_dir = temp_dir.path().join(".github");
    std::fs::create_dir_all(&github_dir).unwrap();
    std::fs::write(
        github_dir.join("PULL_REQUEST_TEMPLATE.md"),
        "## Checklist\n\n- [ ] Template item\n",
    )
    .unwrap();

    let project_id = ProjectId::from_string("project-plan-pr".to_string());
    let mut project = Project::new(
        "Plan project".to_string(),
        temp_dir.path().to_string_lossy().to_string(),
    );
    project.id = project_id.clone();
    project.base_branch = Some("main".to_string());
    let task = Task::new_with_category(
        project_id.clone(),
        "Merge plan".to_string(),
        TaskCategory::PlanMerge,
    );
    let mut plan_branch = PlanBranch::new(
        ArtifactId::from_string("artifact-plan".to_string()),
        IdeationSessionId::from_string("session-plan".to_string()),
        project_id,
        "feature/plan".to_string(),
        "develop".to_string(),
    );
    plan_branch.pr_number = Some(123);

    let github = Arc::new(MockGithubService::new());
    let github_trait: Arc<dyn GithubServiceTrait> = github.clone();
    let publisher = PlanPrPublisher::new(&github_trait, None, None);
    let description = AgentWorkspacePrDescription::new(
        None,
        "## Summary\n\nAgent-written plan PR body".to_string(),
    );

    publisher
        .sync_existing_pr(
            &task,
            &project,
            &plan_branch,
            PrReviewState::Ready,
            &description,
        )
        .await
        .unwrap();

    let state = github.state();
    assert_eq!(state.update_pr_details_calls, 1);
    let (pr_number, title, _) = state
        .last_update_pr_details_args
        .clone()
        .expect("update PR args should be captured");
    assert_eq!(pr_number, 123);
    assert_eq!(title, "Merge plan");
    let body = state.last_update_pr_details_body.as_deref().unwrap();
    assert!(body.starts_with("## Summary\n\nAgent-written plan PR body"));
    assert!(!body.contains("## Checklist"));
    assert!(!body.contains("## RalphX Status"));
    assert!(!body.contains("## How To Review"));
    assert!(body.contains("_No plan artifact was available"));
    assert!(body.contains("<summary>View full plan</summary>"));
    assert!(body.contains("_Generated by [RalphX]("));
}

#[tokio::test]
async fn plan_pr_publisher_rejects_empty_agent_body() {
    let temp_dir = tempfile::tempdir().unwrap();
    let project_id = ProjectId::from_string("project-plan-pr".to_string());
    let mut project = Project::new(
        "Plan project".to_string(),
        temp_dir.path().to_string_lossy().to_string(),
    );
    project.id = project_id.clone();
    let task = Task::new_with_category(
        project_id.clone(),
        "Merge plan".to_string(),
        TaskCategory::PlanMerge,
    );
    let mut plan_branch = PlanBranch::new(
        ArtifactId::from_string("artifact-plan".to_string()),
        IdeationSessionId::from_string("session-plan".to_string()),
        project_id,
        "feature/plan".to_string(),
        "main".to_string(),
    );
    plan_branch.pr_number = Some(123);

    let github = Arc::new(MockGithubService::new());
    let github_trait: Arc<dyn GithubServiceTrait> = github.clone();
    let publisher = PlanPrPublisher::new(&github_trait, None, None);
    let description = AgentWorkspacePrDescription::new(None, "   \n".to_string());

    let result = publisher
        .sync_existing_pr(
            &task,
            &project,
            &plan_branch,
            PrReviewState::Ready,
            &description,
        )
        .await;

    match result {
        Err(AppError::Infrastructure(message)) => {
            assert_eq!(message, "plan PR describer returned an empty PR body");
        }
        Err(other) => panic!("expected infrastructure error, got {other:?}"),
        Ok(_) => panic!("empty agent body should fail before writing PR details"),
    }
    assert_eq!(github.state().update_pr_details_calls, 0);
}

#[test]
fn finalize_body_without_plan_appends_only_footer() {
    let body = finalize_agent_workspace_pr_body("## Summary\n\nBody", &None);
    assert!(body.starts_with("## Summary\n\nBody"));
    assert!(body.contains("_Generated by [RalphX]("));
    assert!(!body.contains("<details>"));
}

#[test]
fn finalize_body_with_empty_plan_appends_only_footer() {
    let body = finalize_agent_workspace_pr_body("## Summary\n\nBody", &Some("  ".to_string()));
    assert!(body.starts_with("## Summary\n\nBody"));
    assert!(body.contains("_Generated by [RalphX]("));
    assert!(!body.contains("<details>"));
}
